[package]
name = "littensy/ripple"
version = "0.7.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["src", "src/**", "default.project.json", "wally.toml", "LICENSE"]

[dependencies]
Promise = "evaera/promise@4.0.0"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
