[package]
name = "littensy/react-ripple"
version = "3.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
	"node_modules",
	"src/__tests__",
	"src/index.d.ts",
	"package.json",
	"React.luau",
	"Ripple.luau",
]

[dependencies]
React = "jsdotlua/react@^17"
Ripple = "littensy/ripple@^0.10"
