[package]
name = "littensy/ripple"
version = "0.10.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["node_modules", "src/__tests__", "src/index.d.ts", "package.json"]

[dependencies]
